#!/bin/sh

[ $# -eq 0 ] && printf "Usage: %s USERNAME\n" "$(basename "$0")" && exit 1

getent passwd "$1" > /dev/null 2>&1 || { printf "Invalid username: %s\n" "$1"; exit 1; }

username="$1"

killall -u  "$username"
userdel -rf "$username"
